--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekRanksUI
build-by-default: true
branches:
- master
projects:
  KygekRanksUI:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
    - src: KygekTeam/ktpmpl-cfs/ktpmpl-cfs
      version: ^1.0
...
