--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekRanksUI
build-by-default: true
branches:
- master
- pm4
projects:
  KygekRanksUI:
    path: ""
    libs:
    - src: Vecnavium/FormsUI/FormsUI
      version: ^1.0.0
    - src: KygekTeam/ktpmpl-cfs/ktpmpl-cfs
      branch: pm4-updatenotifier
      version: ^3.0
...
