---
# KygekRanksUI plugin
# Made by Kygekraqmak and KygekTeam

##### DANGER ZONE #####
# Do not change this (Only for internal use)!
config-version: "2.2"
#######################

# Use "{player}" to show player's name
# Use "&" as formatting codes
# Use "\n" to break into new line

##### COMMANDS #####
# Set the command description of KygekRanksUI
# Leave it empty if you want to use the default description
command-description: ""
# Set command aliases that will open KygekRanksUI when executed (Default command will always be /ranks)
# Do not use "/" in front of the commands!
# Leave it empty if you don't want to use aliases
command-aliases: []
####################

# Title of the main form of KygekRanksUI
# It will be shown right after the player typed the /ranks command
title: " §l§b»§r§7 [§bRanks§7]"
# Content of the main form of KygekRanksUI
# You can add general info about the ranks below
content: "Buy Ranks At: §e+62 813-8647-0421"
# Return button to the main form of KygekRanksUI
# It will be shown in the ranks form and applied globally
return-button: "Return"
# Exit button in the main form of KygekRanksUI
exit-button: "Exit"
# Whether to return to main form when ranks form closed (X button at upper right corner)
return-to-main: true

##### RANKS FORM FORMAT #####
# ranks:                                              --> You will put the ranks menu button, title and content below here.
#   ExampleRank:                                      --> This will just be the identifier for the code to work. You can put anything you like.
#     menu-button: "ExampleRank"                      --> This will be the button of the rank that will be shown in the main form.
#     button-image: "https://example.com/example.png" --> This will be the image shown beside the button in the main form.
#     title: "ExampleRank"                            --> This will be the title of the rank that will be shown in the rank's form.
#     content: "Change in config.yml!"                --> This will be the content of the rank that will be shown in the rank's form.
#############################

# Notes for button-image (not following this may not load the image):
#
# There are 2 modes (texture pack or link). If you want to use image from link, you must follow below:
# - Image should be using the .png format.
# - Image should be 160 x 160 px in size.
# - Image should be displayed as raw (no HTML/CSS/JavaScript included).
# - Link should include "http://" or "https://".
# - Sometimes the image will not load properly, you may have to open status bar or press Windows key.
# - For example, please visit https://kygekdev.github.io/test.png.
#
# If you want to use image from texture pack, please visit https://github.com/KygekDev/default-textures for more info.
#
# Leave button-image empty if you don't want to use any image(s).

# Change here:
ranks:
  S&K:
    menu-button: "Syarat & Ketentuan"
    button-image: ""
    title: " §l§b»§r§7 [§bS&K§7]"
    content: "§l§fSYARAT & KETENTUAN§r\n\n§f===================\n§e»§f Tidak Bisa Reff Saldo/Uang.\n§e»§f Transfer Rank Harus Membayar 5k.\n§e»§f Ganti Gamertag = Rank Hangus.\n§e»§f Jika Membeli Harap Tidak Spam.\n§e»§f Up Season Rank Tidak Akan Hangus.\n§f==================="
  PURPLE:
    menu-button: ""
    button-image: "textures/ui/permissions_member_star"
    title: ""
    content: ""
  VIP:
    menu-button: ""
    button-image: "textures/ui/permissions_member_star"
    title: ""
    content: ""
  # You can add more if you need by following the format above
...
